services:
  - type: web
    name: email-redirect-tool
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: NAMECHEAP_API_USER
        value: YOUR_NAMECHEAP_USERNAME
      - key: NAMECHEAP_API_KEY
        value: YOUR_NAMECHEAP_API_KEY
      - key: NAMECHEAP_USERNAME
        value: YOUR_NAMECHEAP_USERNAME
      - key: NAMECHEAP_CLIENT_IP
        value: 44.226.145.213
        # Note: Render uses multiple outbound IPs. All must be whitelisted in Namecheap:
        # 44.226.145.213, 54.187.200.255, 34.213.214.55, 35.164.95.156, 44.230.95.183, 44.229.200.200
      - key: SECRET_KEY
        value: email-redirect-secure-key-2024-change-in-production
      - key: FLASK_ENV
        value: production
    plan: starter
    region: oregon
    healthCheckPath: /api/health